services:
  backend:
    image: backend
    container_name: backend
    build: ./BackEnd
    ports:
      - "801:8000"
    volumes:
      - ./BackEnd:/usr/src/app
    environment:
      - PYTHONUNBUFFERED=1 

  frontend:
    image: frontend
    container_name: frontend
    build: ./frontend
    ports:
      - "802:3000"
    volumes:
      - ./frontend:/usr/src/app
